module.exports = [
	{ img: 'https://www.injustice.com/storage/characters/batman/thumb.jpg', name: 'batman', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/superman/thumb.jpg', name: 'superman', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/wonder-woman/thumb.jpg', name: 'wonder woman', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/aquaman/thumb.jpg', name: 'aquaman', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/atrocitus/thumb.jpg', name: 'atrocitus', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/supergirl/thumb.jpg', name: 'supergirl', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/gorilla-grodd/thumb.jpg', name: 'gorilla grodd', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/deadshot/thumb.jpg', name: 'deadshot', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/harley-quinn/thumb.jpg', name: 'harley quinn', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/the-flash/thumb.jpg', name: 'the flash', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/blue-beetle/thumb.jpg', name: 'blue beatle', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/black-canary/thumb.jpg', name: 'black canary', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/bane/thumb.jpg', name: 'bane', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/swamp-thing/thumb.jpg', name: 'swamp thing', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/catwoman/thumb.jpg', name: 'catwoman', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/cheetah/thumb.jpg', name: 'cheetah', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/firestorm/thumb.jpg', name: 'firestorm', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/green-lantern/thumb.jpg', name: 'green lantern', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/dr-fate/thumb.jpg', name: 'dr fate', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/green-arrow/thumb.jpg', name: 'green arrow', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/joker/thumb.jpg', name: 'joker', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/red-hood/thumb.jpg', name: 'red hood', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/darkseid/thumb.jpg', name: 'darkseid', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/scarecrow/thumb.jpg', name: 'scarecrow', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/cyborg/thumb.jpg', name: 'cyborg', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/black-adam/thumb.jpg', name: 'black adam', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/raiden/thumb.jpg', name: 'raiden', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/black-manta/thumb.jpg', name: 'black manta', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/brainiac/thumb.jpg', name: 'brainiac', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/captain-cold/thumb.jpg', name: 'captain cold', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/robin/thumb.jpg', name: 'robin', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/poison-ivy/thumb.jpg', name: 'poison ivy', game: 'Injustice 2'},
	{ img: 'https://aa1a5178aef33568e9c4-a77ea51e8d8892c1eb8348eb6b3663f6.ssl.cf5.rackcdn.com/p/full/cc2d1eb9-0f53-47a2-83fd-66f1b906bd9d.jpg', name: 'michelangelo', game: 'Injustice 2'},
	{ img: 'https://aa1a5178aef33568e9c4-a77ea51e8d8892c1eb8348eb6b3663f6.ssl.cf5.rackcdn.com/p/full/a6ebddb2-fa5b-4352-a1e8-da6859d0c06f.jpg', name: 'leonardo', game: 'Injustice 2'},
	{ img: 'https://aa1a5178aef33568e9c4-a77ea51e8d8892c1eb8348eb6b3663f6.ssl.cf5.rackcdn.com/p/full/b2a440ed-4a5b-4d74-a879-50644dd2203e.jpg', name: 'raphael', game: 'Injustice 2'},
	{ img: 'http://necaonline.com/wp-content/uploads/2016/11/590w-quarter-donatello-feat-img.jpg', name: 'donatello', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/enchantress/thumb.jpg', name: 'enchantress', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/hellboy/thumb.jpg', name: 'hellboy', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/atom/thumb.jpg', name: 'atom', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/sub-zero/thumb.jpg', name: 'sub-zero', game: 'Injustice 2'},
	{ img: 'https://www.injustice.com/storage/characters/starfire/thumb.jpg', name: 'starfire', game: 'Injustice 2'},
	{ img: 'https://orig00.deviantart.net/5c3d/f/2013/094/5/9/tien___dragon_ball_online___by_majingoku77-d60ffot.png', name: 'tien', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/deathbattlefanon/images/5/54/Yamcha.png/revision/latest?cb=20150317171234', name: 'yamcha', game: 'Dragonball FighterZ'},
	{ img: 'https://img00.deviantart.net/09b4/i/2017/279/9/6/son_gohan_difinitivo_dbs_by_jaredsongohan-dbpor9o.png', name: 'adult gohan', game: 'Dragonball FighterZ'},
	{ img: 'http://miso.moe/wp-content/uploads/2018/01/krillinp-1-1024x970.png', name: 'krillin', game: 'Dragonball FighterZ'},
	{ img: 'https://pre00.deviantart.net/9c87/th/pre/i/2012/297/4/1/goku_ssj_by_maffo1989-d578nrz.png', name: 'goku ssj', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/goanimate-v2/images/5/5d/Frieza.png/revision/latest?cb=20150503121623', name: 'frieza', game: 'Dragonball FighterZ'},
	{ img: 'https://pre00.deviantart.net/f15c/th/pre/i/2016/056/2/2/android_18__close_up_finished_product__by_anthonyjmo-d9t21n3.png', name: 'android 18', game: 'Dragonball FighterZ'},
	{ img: 'https://img00.deviantart.net/fd47/i/2012/348/1/8/kid_majin_bu_face_by_maffo1989-d5nzq2i.png', name: 'kid buu', game: 'Dragonball FighterZ'},
	{ img: 'https://i.ytimg.com/vi/Y-VKKxQQXQk/maxresdefault.jpg', name: 'captain ginyu', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/omnibattles/images/9/90/Nappa_pose_1_dragon_ball_online_by_majingoku77-d60ey2o.png/revision/latest?cb=20161212164120', name: 'nappa', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/dragonball/images/f/f1/Goku_ssj_blue_3_by_saodvd-danj4c2.png/revision/latest?cb=20180110132504', name: 'goku blue', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/oneminutemelee/images/a/af/Trunks.png/revision/latest?cb=20170205224918', name: 'trunks', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/gameideas/images/3/30/Vegeta_SSJ.png/revision/latest?cb=20171115004655', name: 'vegeta ssj', game: 'Dragonball FighterZ'},
	{ img: 'https://orig00.deviantart.net/bb8b/f/2017/146/9/b/beerus_the_destroyer___god_of_destruction_by_originalsupersaiyan-dbah7vj.png', name: 'beerus', game: 'Dragonball FighterZ'},
	{ img: 'https://i.imgur.com/sW4erDp.jpg', name: 'perfect cell', game: 'Dragonball FighterZ'},
	{ img: 'http://cdn.shopify.com/s/files/1/1716/3519/products/1432007237693_grande.png?v=1501474046', name: 'android 16', game: 'Dragonball FighterZ'},
	{ img: 'https://pre00.deviantart.net/539e/th/pre/i/2018/018/6/d/vegeta_ssj_blue_full_power_by_jaredsongohan-dc0fdvp.png', name: 'vegeta blue', game: 'Dragonball FighterZ'},
	{ img: 'https://wallpapercave.com/wp/4Bs98JW.jpg', name: 'gotenks', game: 'Dragonball FighterZ'},
	{ img: 'https://orig00.deviantart.net/980c/f/2013/094/3/e/piccolo_pose_2___dragon_ball_online___by_majingoku77-d60eyl3.png', name: 'piccolo', game: 'Dragonball FighterZ'},
	{ img: 'https://lh5.googleusercontent.com/-vyH-hHatu7Q/VQyK7RbjYII/AAAAAAAAALQ/VoN5rb4vlZA/w506-h750/1_Teen_Gohan_Super_Saiyan_2_Pic_1.png', name: 'teen gohan', game: 'Dragonball FighterZ'},
	{ img: 'https://t00.deviantart.net/mPVoT3GIWlca8d8zig2OnfbWDso=/fit-in/700x350/filters:fixed_height(100,100):origin()/pre00/c2ce/th/pre/i/2018/027/d/c/majin_android_21_render_by_desertwiggle-dc1ce8b.png', name: 'android 21', game: 'Dragonball FighterZ'},
	{ img: 'https://guides.gamepressure.com/dragon_ball_fighterz/gfx/word/604419945.jpg', name: 'majin buu', game: 'Dragonball FighterZ'},
	{ img: 'https://pre00.deviantart.net/6656/th/pre/i/2017/179/7/4/hit___hitto_by_aashan-dbec5w2.png', name: 'hit', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/villains/images/5/5e/RoseBlack.png/revision/latest?cb=20170702200527', name: 'goku black', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/villains/images/3/31/Lss_broly.png/revision/latest?cb=20130802142809', name: 'broly', game: 'Dragonball FighterZ'},
	{ img: 'https://vignette.wikia.nocookie.net/dbz-vs/images/d/db/Bardock.png/revision/latest?cb=20151218103841', name: 'bardock', game: 'Dragonball FighterZ'}
]






